services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    restart: always
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=n8n.mbs-stettin.de
      - N8N_PROTOCOL=https
      - N8N_PORT=5678
      - WEBHOOK_URL=https://n8n.mbs-stettin.de
      - N8N_EDITOR_BASE_URL=https://n8n.mbs-stettin.de
      - NODE_ENV=production
    volumes:
      - n8n_n8n_data:/home/node/.n8n

volumes:
  n8n_n8n_data:
    external: true
